server:
  port: 8082

spring:
  application:
    name: "stock-tick-consumer-avro"
  datasource:
    url: jdbc:mysql://paydaytrade.caqaqtftfvan.us-west-2.rds.amazonaws.com:3306/payday
    username: admin
    password: gulsahsofttech
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
      time-zone: UTC
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        isolation:
          level: read_committed

    listener:
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
